services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://rihal_user:rihal_pwd@db:5432/rihal_db
    volumes:
      - ./backend:/code
    networks:
      - rihal_network

  db:
    image: postgres:15
    container_name: psql-db
    environment:
      POSTGRES_USER: rihal_user
      POSTGRES_PASSWORD: rihal_pwd
      POSTGRES_DB: rihal_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rihal_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: psql-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@rihal.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - rihal_network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  rihal_network:
    driver: bridge
